#! /bin/sh

sxhkd &

# Gets each monitor and creates a Polybar for each
if type "xrandr"; then
	for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
		MONITOR=$m polybar --reload abyss &
	done
else
	polybar --reload abyss &
fi

# Config for dual monitors
bspc monitor HDMI-A-0 -d I II III IV V
bspc monitor eDP -d VI VII VIII IX X

# Make laptop monitor be positioned on left side
xrandr --output HDMI-A-0 --auto --output eDP --auto --left-of HDMI-A-0

bspc config border_width         1
bspc config window_gap          4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config external_rules_command ~/.config/bspwm/external_rules

bspc rule -a TopTracker state=floating center=true rectangle=1376x625+0+0

# Sets the background wallpaper
feh --bg-center ~/Pictures/Wallpapers/Moon.png ~/Pictures/Wallpapers/Space.jpg
